name: Diu
description: An artificial sunlight project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_blue_plus: ^1.4.0
  blurrycontainer: ^1.0.2
  location: ^4.4.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  # #   - images/a_dot_burr.jpeg
  # #   - images/a_dot_ham.jpeg

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Raleway-VariableFont_wght.ttf
        - asset: fonts/Raleway-Italic-VariableFont_wght.ttf
          style: italic
